### ISSUE TITLE
filmorago (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#100360]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);;
- [X] Filters were updated before reproduced an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) is used?

the problem is with app, not a site

### Which device is used?

Mobile

### Where did you encounter the problem?

https://play.google.com/store/apps/details?id=com.wondershare.filmorago

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

||analytics.300624.com^

</details>

<details><summary>Screenshot 
</summary>

 ![Screenshot_20211117-142717190](https://user-images.githubusercontent.com/87330832/142142585-65e2bfa0-9573-4966-849d-47c4877bcb9b.jpg)

</details>

### Privacy

- [X] I agree to follow this condition
