### ISSUE TITLE
Chinese `Xiaohongshu` (`RED`) tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#100775]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [ ] This is not an ad/bug report.

### Problem description

- https://www.xiaohongshu.com/error?code=423
--> `POST` https://t2.xiaohongshu.com/api/v2/collect
--> `POST` https://lng.xiaohongshu.com/api/collect
--> `GET` https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.3/dist/ErrorTracker.js
--> `GET` https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.0/dist/ErrorTracker.js
--> `Set-Cookie` xhsTrackerId
--> `Set-Cookie` timestamp2.sig  (not sure)
--> `Set-Cookie` timestamp2  (not sure)

### Proposed solution

```
https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.3/dist/ErrorTracker.js
https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.0/dist/ErrorTracker.js
cookie: xhsTrackerId=426644aa-782a-4264-c2f5-97a3d52c82c8; extra_exp_ids=ranchipuar_exp1,commentshow_clt1,gif_exp1,ques_exp1

||fe-static.xhscdn.com/formula-static/@xhs/error-tracker
$cookie=xhsTrackerId
||xiaohongshu.com^$cookie=timestamp2.sig (not sure)
||xiaohongshu.com^$cookie=timestamp2 (not sure)
```

**Comment by Alex-302** [comment]
Do not use `Feature Request` for reporting about filtering issues.

**Comment by Alex-302** [comment]
It seems this is used for bug tracking.
