### ISSUE TITLE
hulu app (ios)

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#104921]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.0

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

hulu.com

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

i came across some unblocked trackers and ad domains while
watching hulu:

||blisspointmedia.com^ (https://www.glassdoor.com/Overview/Working-at-Bliss-Point-Media-EI_IE3284629.11,28.htm)

||brightline.tv^ (data driven advertising)

||pixsrvcs.com^ (https://gist.github.com/rushic24/28a4ac4ff6faf79059b8fd6cc036092c)

||hrzn-nxt.com^ (https://www.eharmony.com/static_cms/eharmony/static/Downloads/eharmony_us_tracking_mechanisms_05nov2019.pdf) (they used multiple subdomains)

app link: https://apps.apple.com/us/app/hulu-watch-tv-series-movies/id376510438

### Privacy

- [X] I agree to follow this condition

**Comment by hitechtalk69** [comment]
sorry i didnt mean the nsfw label my bad

**Comment by hitechtalk69** [comment]
@Alex-302

**Comment by hitechtalk69** [comment]
hi were these figured out? @Alex-302

**Comment by Alex-302** [comment]
I see only one domain in my log, and it is blocked by `||events.brightline.tv^`
