### ISSUE TITLE
Tracking subdomain in app `Vieon`

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdguardFilters#126656]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [ ] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

`https://play.google.com/store/apps/details?id=vieon.phim.tv`

### What filters do you have enabled?

NextDNS with AdGuard DNS filter 

### Add your comment and screenshots

<comment>

- Tracking/Advertising subdomain:	**`sentry.vieon.vn`**
- Android app:	`https://play.google.com/store/apps/details?id=vieon.phim.tv`
- Proposed rule: `||sentry.vieon.vn^`

Logs:

<details>

![log](https://user-images.githubusercontent.com/59459998/183557685-f316fcd5-c6b5-411e-a0a6-691ef38bed2f.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by vhpcdpgl** [comment]
@Yuki2718 @sfionov Anyone can solve the problem?

**Comment by vhpcdpgl** [comment]
@Stillness-2 @jayvdb @sfionov @ptxmac

**Comment by Alex-302** [comment]
sentry is not a tracker
