### ISSUE TITLE
play.google.com has a tracking parameter that has not been removed

### ISSUE THREAD

**Issue by hacamer** [AdguardTeam/AdguardFilters#127580]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [ ] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.9(48)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel&referrer=utm_source%3Dono%26utm_medium%3Dono%26utm_campaign%3D

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

1. There is a tracking parameter that has not been remove
2.  Screenshots
no 

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Please, enable `URL Tracking filter` and `Tracking Protection filter` then check the url again. If you’re still able to reproduce the issue, reopen it here.

**Comment by hacamer** [comment]
@jellizaveta Still not blocked, is that because of this? tks!
![Screenshot_20220819223615](https://user-images.githubusercontent.com/73057402/185643063-b7f6cdc6-0862-4a2e-bc20-0e7f7e3809a6.png)
