### ISSUE TITLE
character.ai

### ISSUE THREAD

**Issue by panty-sniffer** [AdguardTeam/AdguardFilters#191875]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://c.ai

### Ad Blocking

EasyList

### Add your comment and screenshots

yet another [statsig](https://statsig.com/) domain used for extensive data collection. should be blocked globally, not just character.ai

`||prodregistryv2.org^`

### Privacy

- [X] I agree to follow this condition
