### ISSUE TITLE
Add a filter replacing the tracking parameters list in Stealth mode

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/AdguardFilters#57197]
In the CoreLibs 1.6 we are going to remove the tracking parameters list from the Stealth mode configuration and replace it with the new basic rules modifier `$removeparam` which provides enhanced capabilities.
The related issue with the specification: https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/509

So we need a new filter which contains such rules to replace the standard tracking parameters list. Here's the list: utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_referrer, yclid, gclid, fbclid, _openstat, fb_action_ids, fb_comment_id, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map.
In addition to that list we should consider to the parameters from this issue: https://github.com/AdguardTeam/CoreLibs/issues/1184

**Comment by BlazDT** [comment]
Internal facebook tracking ids *taken from our existing rule":

["&eid=" , "%26eid%3D" , "?eid=", "%3Feid%3D", "?__tn__=" , "%3F%5F%5Ftn%5F%5F%3D" , "&__tn__=" , "%26%5F%5Ftn%5F%5F%3D" , "?source=" , "%3Fsource%3D" , "?__xts__" , "%3F%5F%5Fxts%5F%5F" , "&__xts__" , "%26%5F%5Fxts%5F%5F" , "&amp;__xts__%5B" , "?ref=" , "%3Fref%3D" , "?fref=" , "%3Ffref%3D" , "?epa=" , "%3Fepa%3D" , "&ifg=" , "%26ifg%3D" , "?comment_tracking=", "%3Fcomment_tracking%3D" , "?av=", "%3Fav%3D" , "&av=", "%26av%3D", "?acontext=", "%3Facontext%3D", "&session_id=", "%26session_id%3D", "&amp;session_id=", "?hc_location=", "%3Fhc_location%3D", "&fref=", "%26fref%3D" , "?__cft" , "%3f__cft"]

External facebook (removed the ones listed above):
"&fbc=" , "%26fbc%3D" , "?share=" , "%3Fshare%3D" , "%3F__twitter_impression%3D" , "?__twitter_impression=" , "?wtmc=" , "%3Fwtmc%3D" , "?originalReferrer=" , "%3ForiginalReferrer%3D" , "?wtrid=", "%3Fwtrid%3D" , "?trbo=", "%3Ftrbo%3D" , "?GEPC=" , "%3FGEPC%3D", "?whatsapp=" , "%3Fwhatsapp%3D", "?fbc=" , "%3Ffbc%3D", "?dmcid=" , "%3Fdmcid%3D"]

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/78217

**Comment by sxgunchenko** [comment]
Please note, that the `$removeparam` rules' syntax has been changed, see [the spec](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeparam-modifier) for the current one

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers 

Main points:

* This filter's purpose: stripping URLs of common known tracking parameters
* So it would basically consist of `$removeparam` rules
* Needs to be limited to platforms that support these rules (so no iOS, Safari, Android Content Blocker).
* This filter list will replace the tracking parameters list in Stealth Mode. Now when a user opts to block tracking parameters, this filter list will be enabled automatically.

Here's what we need:

* [ ] Filter list name (@AdguardTeam/filters-maintainers, ideas?)
* [ ] Filter list description
* [ ] A pull request here that creates this list
* [ ] Then a pull request to FiltersRegistry that adds this new list
* [ ] And finally a pull request to KB that adds that filter list here: https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/01.adguard-ad-filters/
* [ ] Mention this new list in the filters policy: https://github.com/AdguardTeam/AdguardKnowledgeBase/tree/master/01.general/05.adguard-filter-policy

**Comment by slavaleleka** [comment]
name: AdGuard URL Tracking Parameters filter

description: Protects from tracking via removing query parameters from pages’ URLs.

**Comment by stanislav-atr** [comment]
Maybe we should go with `AdGuard URL Tracking filter` or `AdGuard URL Trackers filter` to shorten it a bit?

**Comment by ameshkov** [comment]
So, the current options are:

* 👍  AdGuard URL Tracking Parameters filter
* 🚀  AdGuard URL Tracking filter
* ❤️  AdGuard URL Trackers filter

@AdguardTeam/filters-maintainers pick your emoji :)

**Comment by Yuki2718** [comment]
I think `URL` in the title is bit redundant. BTW it's better to set the target of the list - I had been a ClearURL user years ago with my own custom whitelist, but finally removed for the amount of trouble I got. Will the list be for everyone and be enabled by default in install navigation, or be for privacy advocates (requiring user to explicitly enable ) with "remove generally, whitelist one by one" approach?

**Comment by ameshkov** [comment]
Yeah, I guess URL is indeed a bit redundant. Or maybe we could make it `AdGuard Tracking Parameters list`, added it as an option.

> Will the list be for everyone and be enabled by default in install navigation, or be for privacy advocates (requiring user to explicitly enable ) with "remove generally, whitelist one by one" approach?

That's a good question.

We'd like to simplify Stealth Mode a little bit (in the browser extension as well).

1. Add a "Block known trackers" checkbox there that will control whether Tracking Protection list is enabled or not.
2. Introduce three levels of protection:
    * Comfortable level: Tracking Protection list
    * High: Tracking Protection filter + Tracking Parameters filter + some options
    * Custom: the user selects what's suitable

I am not yet sure about the tracking parameters filter though. It may very well be placed to the "Comfortable" level.

**Comment by Yuki2718** [comment]
> I am not yet sure about the tracking parameters filter though. It may very well be placed to the "Comfortable" level.

TBH that all depends on how we write filters: "remove as much as possible and fix individually" vs. "remove only safe ones, gradually expands" are the both ends.

**Comment by ameshkov** [comment]
Well, I'd definitely prefer the safe approach :)

**Comment by Alex-302** [comment]
3. https://github.com/AdguardTeam/AdguardFilters/pull/80517
4. https://github.com/AdguardTeam/FiltersRegistry/pull/460
